Add optics-sop and metametapost GHC-8.10 travis jobs

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,7 +4,7 @@
 #
 # For more information, see https://github.com/haskell-CI/haskell-ci
 #
-# version: 0.9.20200325
+# version: 0.9.20200326
 #
 version: ~> 1.0
 language: c
@@ -116,12 +116,30 @@ install:
     echo "packages: optics" >> cabal.project
     echo "packages: optics-core" >> cabal.project
     echo "packages: optics-extra" >> cabal.project
-    if $GHCJS || ! $GHCJS && [ $HCNUMVER -lt 81000 ] ; then echo "packages: optics-sop" >> cabal.project ; fi
+    echo "packages: optics-sop" >> cabal.project
     echo "packages: optics-th" >> cabal.project
     echo "packages: optics-vl" >> cabal.project
     echo "packages: indexed-profunctors" >> cabal.project
     echo "packages: template-haskell-optics" >> cabal.project
-    if ! $GHCJS && [ $HCNUMVER -lt 81000 ] ; then echo "packages: metametapost" >> cabal.project ; fi
+    if ! $GHCJS ; then echo "packages: metametapost" >> cabal.project ; fi
+  - echo 'package optics' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package optics-core' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package optics-extra' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package optics-sop' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package optics-th' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package optics-vl' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package indexed-profunctors' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package template-haskell-optics' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - if ! $GHCJS ; then echo 'package metametapost' >> cabal.project ; fi
+  - "if ! $GHCJS ; then echo '  ghc-options: -Werror=missing-methods' >> cabal.project ; fi"
   - |
   - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(indexed-profunctors|metametapost|optics|optics-core|optics-extra|optics-sop|optics-th|optics-vl|template-haskell-optics)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
@@ -165,12 +183,30 @@ script:
     echo "packages: ${PKGDIR_optics}" >> cabal.project
     echo "packages: ${PKGDIR_optics_core}" >> cabal.project
     echo "packages: ${PKGDIR_optics_extra}" >> cabal.project
-    if $GHCJS || ! $GHCJS && [ $HCNUMVER -lt 81000 ] ; then echo "packages: ${PKGDIR_optics_sop}" >> cabal.project ; fi
+    echo "packages: ${PKGDIR_optics_sop}" >> cabal.project
     echo "packages: ${PKGDIR_optics_th}" >> cabal.project
     echo "packages: ${PKGDIR_optics_vl}" >> cabal.project
     echo "packages: ${PKGDIR_indexed_profunctors}" >> cabal.project
     echo "packages: ${PKGDIR_template_haskell_optics}" >> cabal.project
-    if ! $GHCJS && [ $HCNUMVER -lt 81000 ] ; then echo "packages: ${PKGDIR_metametapost}" >> cabal.project ; fi
+    if ! $GHCJS ; then echo "packages: ${PKGDIR_metametapost}" >> cabal.project ; fi
+  - echo 'package optics' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package optics-core' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package optics-extra' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package optics-sop' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package optics-th' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package optics-vl' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package indexed-profunctors' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package template-haskell-optics' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - if ! $GHCJS ; then echo 'package metametapost' >> cabal.project ; fi
+  - "if ! $GHCJS ; then echo '  ghc-options: -Werror=missing-methods' >> cabal.project ; fi"
   - |
   - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(indexed-profunctors|metametapost|optics|optics-core|optics-extra|optics-sop|optics-th|optics-vl|template-haskell-optics)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
@@ -196,17 +232,17 @@ script:
   - (cd ${PKGDIR_optics} && ${CABAL} -vnormal check)
   - (cd ${PKGDIR_optics_core} && ${CABAL} -vnormal check)
   - (cd ${PKGDIR_optics_extra} && ${CABAL} -vnormal check)
-  - if $GHCJS || ! $GHCJS && [ $HCNUMVER -lt 81000 ] ; then (cd ${PKGDIR_optics_sop} && ${CABAL} -vnormal check) ; fi
+  - (cd ${PKGDIR_optics_sop} && ${CABAL} -vnormal check)
   - (cd ${PKGDIR_optics_th} && ${CABAL} -vnormal check)
   - (cd ${PKGDIR_optics_vl} && ${CABAL} -vnormal check)
   - (cd ${PKGDIR_indexed_profunctors} && ${CABAL} -vnormal check)
   - (cd ${PKGDIR_template_haskell_optics} && ${CABAL} -vnormal check)
-  - if ! $GHCJS && [ $HCNUMVER -lt 81000 ] ; then (cd ${PKGDIR_metametapost} && ${CABAL} -vnormal check) ; fi
+  - if ! $GHCJS ; then (cd ${PKGDIR_metametapost} && ${CABAL} -vnormal check) ; fi
   # haddock...
   - if ! $GHCJS ; then ${CABAL} v2-haddock $WITHCOMPILER --with-haddock $HADDOCK ${TEST} ${BENCH} all ; fi
   # Building without installed constraints for packages in global-db...
   - rm -f cabal.project.local
   - ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks all
 
-# REGENDATA ("0.9.20200325",["--config=cabal.haskell-ci","cabal.project"])
+# REGENDATA ("0.9.20200326",["--config=cabal.haskell-ci","cabal.project"])
 # EOF
